feat: add delete task rpc implement by checking task status and recla…
dragonflyoss/client pull request #560
Opened 2024-06-26 16:08 UTC by IRONICBo

## Description

This pull request adds functionality to check task status and handle status data within the `dfdaemon_download` and `task` modules. The implementation includes new methods for deleting tasks and reclaiming local storage.

## Related Issue

- https://github.com/dragonflyoss/Dragonfly2/issues/2818

## Motivation and Context

The changes are required to improve the task management capabilities of the system. By adding these methods, users can better manage and delete tasks, ensuring efficient resource usage and task tracking.

- Design: https://www.yuque.com/baimo/fv9qk8/ed40b9sg7l9crdt4
- Design: https://github.com/dragonflyoss/Dragonfly2/issues/2818#issuecomment-2190419157

## Screenshots (if appropriate)

2024-07-01 03:19 UTC, gaius-qi requested changes

2024-07-01 03:19 UTC, gaius-qi commented on dragonfly-client/src/task/mod.rs
> +            if task.is_started() && task.is_uploading() {
```rust
if !task.is_finished() || task.is_uploading() {
```

2024-07-01 03:19 UTC, gaius-qi commented on dragonfly-client/src/grpc/dfdaemon_download.rs
> +        // Clone the request.
DfdaemonUpload also needs to add DeleteTask.

2024-07-01 03:19 UTC, gaius-qi commented on dragonfly-client/src/grpc/dfdaemon_download.rs
> +        self.task.delete_task(task_id.as_str()).await.map_err(|e| {
User `err`.

2024-07-01 03:19 UTC, gaius-qi commented on dragonfly-client/src/task/mod.rs
> +                .or_err(ErrorType::StorageError)?;
Print error log for storage error.

2024-07-01 03:19 UTC, gaius-qi commented on dragonfly-client/src/task/mod.rs
> +        if let Some(task) = self.storage.get_task(task_id)? {
If task is not exist, print error log.

2024-07-02 00:51 UTC, IRONICBo commented on dragonfly-client/src/task/mod.rs
> +            if task.is_started() && task.is_uploading() {
```rs
    // is_started returns whether the task downloads started.
    pub fn is_started(&self) -> bool {
        self.finished_at.is_none()
    }
    
    // is_finished returns whether the task downloads finished.
    pub fn is_finished(&self) -> bool {
        self.finished_at.is_some()
    }

2024-07-02 00:55 UTC, IRONICBo commented on dragonfly-client/src/grpc/dfdaemon_download.rs
> +        // Clone the request.
OK, I have complete the `delete_cache_task` function in `dragonfly-client/src/grpc/dfdaemon_upload.rs`.

2024-07-02 00:57 UTC, IRONICBo commented on dragonfly-client/src/task/mod.rs
> +        if let Some(task) = self.storage.get_task(task_id)? {
OK!

2024-07-02 01:05 UTC, IRONICBo commented on dragonfly-client/src/grpc/dfdaemon_download.rs
> +        self.task.delete_task(task_id.as_str()).await.map_err(|e| {
Does that mean it needs to be changed to `Status::invalid_argument` return type? But here it looks like there is an error in calling the delete task internal method of the task.

2024-07-02 12:19 UTC, IRONICBo commented on dragonfly-client/src/grpc/dfdaemon_download.rs
> +        self.task.delete_task(task_id.as_str()).await.map_err(|e| {
Ok, fixed.

2024-07-04 02:42 UTC, gaius-qi approved these changes
LGTM

2024-07-04 02:52 UTC, gaius-qi approved these changes
LGTM

2024-07-04 02:53 UTC, merged