S3 Support for Single File Download
dragonflyoss/client pull request #577
Opened 2024-07-08 10:37 UTC by Zyyeric

## Description

The pull request adds AWS S3 Support for single file download in the `dragonfly-client-backend` trait through the use of [Apache OpenDAL](https://github.com/apache/opendal) which provides an interface to interact with the s3 storage system. 

## Related Issue
https://github.com/dragonflyoss/client/issues/495

## Motivation and Context
Currently, Dragonfly rust client does not support back-to-source downloading in AWS S3 protocol. Thus, this implementation based on `backend` trait aims to add such functionality to the system. 

Referenced projects:
- https://github.com/risingwavelabs/risingwave
- https://github.com/apache/opendal

2024-07-15 01:27 UTC, BruceAko commented
Please refer to [conventional commits](https://www.conventionalcommits.org/zh-hans/v1.0.0/) and change the commit messages. @Zyyeric

2024-07-15 01:41 UTC, BruceAko requested changes

2024-07-15 01:41 UTC, BruceAko commented on dragonfly-client-backend/src/s3.rs
> +// Config for AWS S3 Parsed from the S3 URl.
URL or url, not URl.

2024-07-15 01:41 UTC, BruceAko commented on dragonfly-client-backend/src/lib.rs
> +    // the configuration of the Object Storage Services
Missing ending "."

2024-07-15 01:41 UTC, BruceAko commented on dragonfly-client-backend/src/lib.rs
> +    // the configuration of the Object Storage Services
Missing ending "."

2024-07-15 01:41 UTC, BruceAko commented on dragonfly-client-backend/src/s3.rs
> +        // Configure and build the S3 Operator
Missing ending "."

2024-07-15 01:41 UTC, BruceAko commented on dragonfly-client-backend/src/s3.rs
> +        // Configure and build the S3 Operator
Missing ending "."

2024-07-15 02:03 UTC, BruceAko requested changes

2024-07-15 02:03 UTC, BruceAko commented on dragonfly-client-backend/src/s3.rs
> +
Please remove the extra line.

2024-07-16 02:42 UTC, gaius-qi requested changes

2024-07-16 02:42 UTC, gaius-qi commented on dragonfly-client-backend/src/s3.rs
> +        let bucket = url
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html

2024-07-16 02:51 UTC, gaius-qi approved these changes
LGTM

2024-07-16 02:51 UTC, merged