feat: support OSS protocol to download single file
dragonflyoss/client pull request #583
Opened 2024-07-08 14:51 UTC by Lzzzzzt

## Description

This PR add support for Aliyun OSS protocol to download **ONE** file.

This PR is done by the following task:
- [x] Add object storage related information such `access_key_id` (mostly about the security) in the `HeadRequest`, `GetRequest` and other position that need this information
- [x] Add a `OSSConfig` struct that parse request url and store the object storage related information such as `endpoint`, `bucket` and so on.
- [x] Add a `OSS` struct that implements the `Backend` traits and using [OpenDAL](https://github.com/apache/opendal) to access the Aliyun OSS System

Also, the `HeadRequest` now support list directory (recursively)

## Related Issue

#496 

## Motivation and Context

Dragonfly rust client does not support back-to-source downloading of different object storage protocols. Priority is given to supporting OSS protocol back-to-source downloads. Need to support OSS protocol in dragonfly-client-backend crate, implemented based on trait Backend and it needs to support directory recursive downloading.

2024-07-11 09:50 UTC, BruceAko requested changes

2024-07-11 09:50 UTC, BruceAko commented on dragonfly-client-backend/src/oss.rs
> +    async fn get(&self, request: GetRequest) -> Result<GetResponse<Body>> {
How about add some comments for the usage of `get()`?

2024-07-11 09:50 UTC, BruceAko commented on dragonfly-client-backend/src/lib.rs
> +    // entries the the entries of directory.
Please fix the typo here.

2024-07-11 09:52 UTC, Lzzzzzt commented on dragonfly-client-backend/src/lib.rs
> +    // entries the the entries of directory.
ok

2024-07-11 10:03 UTC, BruceAko requested changes

2024-07-11 10:03 UTC, BruceAko commented on dragonfly-client-backend/src/oss.rs
> +    fn key(&self) -> &str {
How about leave some comments or give some examples here?

2024-07-11 10:03 UTC, BruceAko commented on dragonfly-client-backend/src/oss.rs
> +        let mut stat_operator = operator.stat_with(config.key());
How about write some comments here for the code below?

2024-07-11 10:03 UTC, BruceAko commented on dragonfly-client-backend/src/oss.rs
> +        let reader = reader_operator.await.map_err(|err| {
How about write some comments here for the code below?

2024-07-11 10:20 UTC, Lzzzzzt commented on dragonfly-client-backend/src/oss.rs
> +    async fn head(&self, request: HeadRequest) -> Result<HeadResponse> {
I think functions define in a trait, the doc should be at the trait's definition.

2024-07-11 10:27 UTC, BruceAko commented on dragonfly-client-backend/src/oss.rs
> +    async fn head(&self, request: HeadRequest) -> Result<HeadResponse> {
![image](https://github.com/dragonflyoss/client/assets/57183262/3293a573-17e2-4108-98e8-4ec47dc4153b)
Please refer to this. @Lzzzzzt

2024-07-11 10:29 UTC, Lzzzzzt commented on dragonfly-client-backend/src/oss.rs
> +    async fn head(&self, request: HeadRequest) -> Result<HeadResponse> {
but this comment explains nothing

2024-07-11 10:43 UTC, BruceAko commented on dragonfly-client-backend/src/oss.rs
> +    async fn head(&self, request: HeadRequest) -> Result<HeadResponse> {
![image](https://github.com/dragonflyoss/client/assets/57183262/65b182f0-66af-4b2e-b68d-758d546a2bac)
This function is commented all over the project. Please check the code carefully :)

2024-07-15 01:31 UTC, BruceAko requested changes

2024-07-15 01:31 UTC, BruceAko commented on dragonfly-client-backend/src/oss.rs
> +use std::{
Please insert Copyright.

2024-07-15 04:01 UTC, gaius-qi approved these changes
LGTM

2024-07-15 04:07 UTC, merged