feat(scheduler): add automatic scheduler switching feature
dragonflyoss/client pull request #591
Opened 2024-07-15 09:37 UTC by PoloDyBala

## Description

To address potential issues with Scheduler failures during P2P downloads, this project aims to implement an automatic switching feature at the Peer node. When a Scheduler encounters an issue and cannot properly handle downloads, the Peer node will switch to other Scheduler nodes using a hash ring to continue the download, thereby preventing download failures and improving success rates.

## Requirements

1. Scheduler Availability Check During Peer Registration: Ensure that the Scheduler is available during the Peer node registration process.

2. Automatic Scheduler Switching: If the current Scheduler is unavailable, automatically switch to another Scheduler node until a usable Scheduler is found.

3. Feature Development: Complete the development of the automatic switching logic and Scheduler availability detection.
Testing: Implement unit tests and end-to-end (E2E) tests to ensure the reliability and stability of the feature.
## Related Issue

- [https://github.com/dragonflyoss/client/issues/551](url)

## Motivation and Context

Please refer to the following document link for detailed instructions

- [https://www.yuque.com/baimo/fv9qk8/ghfsq8uldrer2p7r](url)

2024-07-21 08:58 UTC, xujihui1985 commented on dragonfly-client/src/grpc/scheduler.rs
> +            let unavailable_scheduler_addrs = self.unavailable_scheduler_addrs.read().await;
there is a potential issue with acquiring both read and write locks on unavailable_scheduler_addrs without properly releasing the read lock first, and do we need async lock here? I don't see a sign the lock is cross the await boundary

2024-07-21 09:01 UTC, xujihui1985 commented
after drop the unavailable_scheduler_addrs, is there any mechanism that the addr will be add back when the scheduler instance work normally?

2024-07-22 00:10 UTC, PoloDyBala commented on dragonfly-client/src/grpc/scheduler.rs
> +            let unavailable_scheduler_addrs = self.unavailable_scheduler_addrs.read().await;
resolved

2024-07-22 00:16 UTC, PoloDyBala commented
> after drop the unavailable_scheduler_addrs, is there any mechanism that the addr will be add back when the scheduler instance work normally?

The design intent is for `unavailable_scheduler_addrs` to be valid only during the interval between two refreshes. Therefore, when `available_scheduler_addrs` is updated, the corresponding `unavailable_scheduler_addrs` will be released.

2024-08-26 00:49 UTC, BruceAko requested changes

2024-08-26 00:49 UTC, BruceAko commented on dragonfly-client/src/grpc/health.rs
> + use dragonfly_client_core::{
Please remove the changes on this line or it will not pass the lint test.

2024-08-26 00:59 UTC, BruceAko requested changes

2024-08-26 00:59 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
>  // use crate::dynconfig::Dynconfig;
Please remove this line or add a blank line to the previous line.

2024-08-26 01:02 UTC, BruceAko requested changes

2024-08-26 01:02 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> -
Please do not remove this blank line.

2024-08-26 02:04 UTC, BruceAko requested changes

2024-08-26 02:05 UTC, BruceAko requested changes

2024-08-26 02:05 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                    .or_insert_with(std::time::Instant::now);
`Instant::now` is enough

2024-08-26 02:05 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                        .or_insert_with(std::time::Instant::now);
ditto

2024-08-26 02:05 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                        .or_insert_with(std::time::Instant::now);
ditto

2024-08-26 02:05 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                            .or_insert_with(std::time::Instant::now);
ditto

2024-08-26 02:30 UTC, BruceAko requested changes

2024-08-26 02:30 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                    assert!(true, "Expected ExceededMaxAttempts error.");
`assert!(true)` will be optimized out by the compiler. Please use `assert_eq!(e, Error::ExceededMaxAttempts, "Expected ExceededMaxAttempts error.");` instead.

2024-08-26 02:30 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                assert!(false, "Client should not connect successfully.");
`assert!(false, ..)` should probably be replaced by `panic!(..)` or `unreachable!(..)`

2024-08-26 02:30 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                    assert!(false, "Unexpected error type.");
ditto

2024-08-26 02:30 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                assert!(false, "Client should connect successfully.")
ditto

2024-08-26 02:30 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                                assert!(false, "Unexpected error type.");
ditto

2024-08-26 02:30 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                            assert!(false, "Client should connect successfully.")
ditto

2024-08-26 02:30 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +                assert!(false, "One of the tasks panicked.");
ditto

2024-09-29 04:00 UTC, gaius-qi approved these changes
LGTM

2024-09-29 04:01 UTC, merged