[WIP]feat: peer automatically injects existing task metadata to scheduler upon restart
dragonflyoss/client pull request #612
Opened 2024-07-18 07:21 UTC by BruceAko

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate)

2024-07-23 12:13 UTC, gaius-qi requested changes
Use hashring.

2024-08-02 03:34 UTC, BruceAko commented
> Use hashring.

resolved

2024-08-02 19:00 UTC, gaius-qi requested changes

2024-08-02 19:00 UTC, gaius-qi commented on dragonfly-client/src/announcer/mod.rs
> +        for request in announcer
Needs to be optimized into a function.

2024-08-02 19:00 UTC, gaius-qi commented on dragonfly-client/src/announcer/mod.rs
> +            let task_id = request.peers[0].task.as_ref().unwrap().id.clone();
Do not use unwarp() in function.

2024-08-02 19:00 UTC, gaius-qi commented on dragonfly-client/src/announcer/mod.rs
> +        let mut peer_map = HashMap::new();
Rename to peers.

2024-08-03 05:36 UTC, BruceAko commented on dragonfly-client/src/announcer/mod.rs
> +        for request in announcer
Resolved.

2024-08-03 05:36 UTC, BruceAko commented on dragonfly-client/src/announcer/mod.rs
> +            let task_id = request.peers[0].task.as_ref().unwrap().id.clone();
Resolved.

2024-08-03 05:36 UTC, BruceAko commented on dragonfly-client/src/announcer/mod.rs
> +        let mut peer_map = HashMap::new();
Resolved.

2024-08-03 05:39 UTC, BruceAko commented
All the problems are resolved, PTAL. Thanks! 😄
@gaius-qi

2024-08-03 06:47 UTC, BruceAko commented
All problems resolve, PTAL. Thanks! 😄
@gaius-qi

2024-08-05 12:32 UTC, gaius-qi requested changes

2024-08-05 12:32 UTC, gaius-qi commented on dragonfly-client/src/announcer/mod.rs
> +                storage.delete_task(&task.id).await;
Remove.

2024-08-05 12:32 UTC, gaius-qi commented on dragonfly-client/src/announcer/mod.rs
> +                    content: None,
Use default valuse.

2024-08-09 03:43 UTC, BruceAko commented on dragonfly-client/src/announcer/mod.rs
> +                storage.delete_task(&task.id).await;
Resolved.

2024-08-09 03:43 UTC, BruceAko commented on dragonfly-client/src/announcer/mod.rs
> +                    content: None,
Resolved.

2024-08-09 04:22 UTC, gaius-qi requested changes

2024-08-09 04:22 UTC, gaius-qi commented on dragonfly-client/src/announcer/mod.rs
> +    async fn announce_peers(
Join Set.

2024-08-09 05:12 UTC, BruceAko commented on dragonfly-client/src/announcer/mod.rs
> +    async fn announce_peers(
Resolved.

2024-08-20 01:36 UTC, IRONICBo commented on dragonfly-client-storage/src/lib.rs
> +    // get_pieces returns the piece metadatas.
It is better to synchronize with the comments below:
```rs
// get_pieces gets the piece metadatas.
pub fn get_pieces(&self, task_id: &str) -> Result<Vec<Piece>> {
    let iter = self.db.prefix_iter::<Piece>(task_id.as_bytes())?;
    iter.map(|ele| ele.map(|(_, piece)| piece)).collect()
}
```

2024-08-20 01:36 UTC, IRONICBo commented on dragonfly-client/src/grpc/scheduler.rs
> +    pub hashring: Arc<RwLock<HashRing<VNode>>>,
It is better to add a public function to access this hashring rather than modifying the property directly.

2024-08-23 12:11 UTC, BruceAko commented on dragonfly-client/src/grpc/scheduler.rs
> +    pub hashring: Arc<RwLock<HashRing<VNode>>>,
Resolved.

2024-08-23 12:17 UTC, BruceAko commented on dragonfly-client-storage/src/lib.rs
> +    // get_pieces returns the piece metadatas.
Resolved.

2024-09-06 07:52 UTC, closed without merging