feat: implement recursive download for dfget
dragonflyoss/client pull request #613
Opened 2024-07-18 11:09 UTC by Lzzzzzt

implement recursive download for dfget

## Description

This PR completes with the following tasks:

- [x] add new function called `download_tasks` to download the directory
- [x] add new function called `download_task` to download single file

Other details will be shown in the code. 

## Related Issue

#496 

## Motivation and Context

Dragonfly rust client does not support back-to-source downloading of different object storage protocols. Priority is given to supporting OSS protocol back-to-source downloads. Need to support OSS protocol in dragonfly-client-backend crate, implemented based on trait Backend and it needs to support directory recursive downloading.

## Screenshots

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/d642305b-0f78-4c30-b41a-67c0cedbc4ea">

2024-07-18 11:54 UTC, BruceAko requested changes

2024-07-18 11:54 UTC, BruceAko commented on dragonfly-client/src/bin/dfget/main.rs
> +        let url: Url = entry.url.parse().expect("unexpected url");
How about returning an error instead of panic?

2024-07-18 11:54 UTC, BruceAko commented on dragonfly-client/src/bin/dfget/main.rs
> +        help = "Specify the max number of file to download"
Specify the `maximum` number of `files` to download.

2024-07-18 11:54 UTC, BruceAko commented on dragonfly-client/src/bin/dfget/main.rs
> +    download_max_files: usize,
Unusual naming.
![image](https://github.com/user-attachments/assets/96dd56d2-d22d-410e-86e6-0fb1676a998d)

2024-07-18 11:54 UTC, BruceAko commented on dragonfly-client/src/bin/dfget/main.rs
> +        help = "Specify the concurrent count of download task"
tasks

2024-07-18 11:54 UTC, BruceAko commented on dragonfly-client/src/bin/dfget/main.rs
> +    // If url end with '/', treat it as a directory and download the whole directory.
ends

2024-07-18 11:54 UTC, BruceAko commented on dragonfly-client/src/bin/dfget/main.rs
> +    // Init the backend factory to choose which backend to use for send head request.
sending

2024-07-18 11:56 UTC, BruceAko commented
Redundant signature information.
![image](https://github.com/user-attachments/assets/7390dc93-5ec1-4479-9894-2e5df068cc03)

2024-07-18 11:58 UTC, Lzzzzzt commented on dragonfly-client/src/bin/dfget/main.rs
> +    download_max_files: usize,
this follow the other naming in the dfget

2024-07-18 12:04 UTC, Lzzzzzt commented on dragonfly-client/src/bin/dfget/main.rs
> +        help = "Specify the max number of file to download"
follow by the other `help` in the dfget

2024-07-19 06:16 UTC, gaius-qi approved these changes
LGTM

2024-07-19 06:16 UTC, merged