test: add unitest for oss
dragonflyoss/client pull request #647
Opened 2024-08-05 07:01 UTC by Lzzzzzt

Add some basic unitest for oss in object storage

## Description

This PR is done by finishing the following tasks:

- [x] bump opendal version to 0.48.0
- [x] change mock framework from `httpmock` to `wiremock`
    - `httpmock` does not support specify the port, but unitest need to.
- [x] add unitest for `ParsedURL` and `ObjectStorage`
- [x] adn unitest for OSS part of `ObjectStorage` 

More details are shown in the code

## Related Issue

#496 
#399

## Motivation and Context

Dragonfly rust client does not support back-to-source downloading of different object storage protocols. Priority is given to supporting OSS protocol back-to-source downloads. Need to support OSS protocol in dragonfly-client-backend crate, implemented based on trait Backend and it needs to support directory recursive downloading.

2024-08-05 12:15 UTC, gaius-qi requested changes

2024-08-05 12:15 UTC, gaius-qi commented on dragonfly-client-backend/Cargo.toml
> +serial_test = "3.1.0"
Remove.

2024-08-23 09:08 UTC, gaius-qi requested changes

2024-08-23 09:08 UTC, gaius-qi commented on dragonfly-client-backend/src/object_storage.rs
> +            builder = builder.region(region);
Why use `builder = builder.region(region);`?

2024-08-23 10:05 UTC, Lzzzzzt commented on dragonfly-client-backend/src/object_storage.rs
> +            builder = builder.region(region);
opendal change its API in https://github.com/apache/opendal/pull/4968

2024-08-26 02:57 UTC, gaius-qi approved these changes
LGTM

2024-08-26 02:57 UTC, merged