add crc32 algorithm with few tests
dragonflyoss/client pull request #684
Opened 2024-08-19 15:29 UTC by CormickKneey

## Description
Implemented the digest crc32 algorithm with some ut

2024-08-19 16:35 UTC, gaius-qi requested changes

2024-08-19 16:35 UTC, gaius-qi commented on dragonfly-client-util/src/digest/mod.rs
> +            let mut buffer = Vec::new();
Need to set the buffer size and read the buffer of the file in a loop to update the hash.

2024-08-19 16:40 UTC, gaius-qi commented
@CormickKneey Fix lint and sign commits refer to https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification.

2024-08-20 03:55 UTC, CormickKneey commented
PTL,bro! @gaius-qi

2024-08-22 13:21 UTC, gaius-qi approved these changes
LGTM

2024-08-22 13:27 UTC, merged